In [2]:
import pandas as pd

a = pd.read_csv("../../data/csv_files/field_f4")

a.describe()

,s_b,s_w,LAI,irr,temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_10m,wind_direction_100m,soil_temperature_0_to_7cm,...,BP,temperature_2m_f,relative_humidity_2m_f,cloud_cover_f,wind_speed_10m_f,wind_direction_10m_f,soil_temperature_0cm_f,soil_temperature_6cm_f,soil_temperature_18cm_f,rain_f
count,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,...,3588.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000
mean,24.121808,22.604939,1.188006,0.038431,14.345199,70.827157,41.683257,7.620476,183.669191,14.651014,...,100694.328317,13.853016,76.216121,49.873140,7.539383,182.789830,13.920530,14.044658,14.202083,0.011388
std,3.652426,2.944436,0.896350,0.887344,4.645678,16.477869,41.383848,5.576626,105.192969,4.289265,...,665.840142,5.042117,16.355248,39.298694,5.979024,96.809663,6.680968,4.469474,3.015177,0.148942
min,15.410000,13.390000,0.000000,0.000000,3.000000,20.000000,0.000000,0.000000,0.000000,5.600000,...,98770.000000,-0.600000,27.000000,0.000000,0.000000,1.000000,-1.100000,4.100000,8.100000,0.000000
25%,22.710000,21.660000,0.249912,0.000000,10.800000,59.000000,1.000000,3.600000,64.000000,11.500000,...,100210.000000,10.300000,64.000000,5.000000,3.600000,120.000000,8.900000,10.700000,11.800000,0.000000
50%,24.560000,23.070000,1.670000,0.000000,14.200000,72.000000,24.000000,6.400000,221.000000,14.400000,...,100650.000000,14.100000,79.000000,51.000000,5.200000,198.000000,13.300000,14.000000,13.900000,0.000000
75%,26.427500,24.230000,1.800000,0.000000,17.500000,84.000000,94.000000,10.200000,258.000000,17.500000,...,101270.000000,17.400000,90.000000,92.000000,10.300000,240.000000,18.600000,17.000000,16.400000,0.000000
max,31.360000,31.300000,2.840000,23.610000,27.000000,100.000000,100.000000,36.700000,360.000000,26.500000,...,102470.000000,26.800000,100.000000,100.000000,37.000000,360.000000,33.200000,26.500000,21.900000,4.000000

In [4]:
a = pd.read_csv("../../data/csv_files/field_f2")

a.describe()

,s_b,s_w,LAI,irr,temperature_2m,relative_humidity_2m,cloud_cover,wind_speed_10m,wind_direction_100m,soil_temperature_0_to_7cm,...,BP,temperature_2m_f,relative_humidity_2m_f,cloud_cover_f,wind_speed_10m_f,wind_direction_10m_f,soil_temperature_0cm_f,soil_temperature_6cm_f,soil_temperature_18cm_f,rain_f
count,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,...,3588.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000,3697.000000
mean,22.669345,19.324451,1.292894,0.063664,14.345199,70.827157,41.683257,7.620476,183.669191,14.651014,...,100694.328317,13.853016,76.216121,49.873140,7.539383,182.789830,13.920530,14.044658,14.202083,0.011388
std,3.982091,4.154420,1.094484,1.504817,4.645678,16.477869,41.383848,5.576626,105.192969,4.289265,...,665.840142,5.042117,16.355248,39.298694,5.979024,96.809663,6.680968,4.469474,3.015177,0.148942
min,13.870000,10.680000,0.000000,0.000000,3.000000,20.000000,0.000000,0.000000,0.000000,5.600000,...,98770.000000,-0.600000,27.000000,0.000000,0.000000,1.000000,-1.100000,4.100000,8.100000,0.000000
25%,20.290000,16.610000,0.081053,0.000000,10.800000,59.000000,1.000000,3.600000,64.000000,11.500000,...,100210.000000,10.300000,64.000000,5.000000,3.600000,120.000000,8.900000,10.700000,11.800000,0.000000
50%,23.860000,20.700000,1.320000,0.000000,14.200000,72.000000,24.000000,6.400000,221.000000,14.400000,...,100650.000000,14.100000,79.000000,51.000000,5.200000,198.000000,13.300000,14.000000,13.900000,0.000000
75%,25.570000,22.480000,2.380000,0.000000,17.500000,84.000000,94.000000,10.200000,258.000000,17.500000,...,101270.000000,17.400000,90.000000,92.000000,10.300000,240.000000,18.600000,17.000000,16.400000,0.000000
max,29.950000,29.680000,2.890000,42.070000,27.000000,100.000000,100.000000,36.700000,360.000000,26.500000,...,102470.000000,26.800000,100.000000,100.000000,37.000000,360.000000,33.200000,26.500000,21.900000,4.000000